vocab_list = [
    "just - shunchaki",
    "think - o'ylamoq",
    "want - xohlamoq",
    "here - bu yerda",
    "really - rosdan; juda",
    "good - yaxshi",
    "make - yasamoq, yaratmoq",
    "thing - narsa",
    "mean - anglatmoq; demoqchi bo'lmoq; -moqchi bo'lmoq",
    "sorry - uzr",
    "there - u yerda",
    "great - zo'r",
    "right - to'g'ri; o'ng",
    "then - keyin",
    "talk - gaplashmoq",
    "look - ko'rinmoq; ko'rinish",
    "need - ga kerak(verb)",
    "guy - bola, odam",
    "little - kichkina",
    "too - ham; juda",
    "way - yo'l",
    "never - hech qachon",
    "call - qo'ng'iroq qilmoq",
    "thank - rahmat aytmoq",
    "wait - kutmoq",
    "come - kelmoq",
    "maybe - balki",
    "back - orqaga",
    "day - kun",
    "people - odamlar",
    "man - erkak; odam",
    "let - qo'yib bermoq, ruxsat bermoq",
    "feel - xis qilmoq",
    "happen - yuz bermoq",
    "please - iltimos",
    "big - katta",
    "still - haliyam",
    "very - juda",
    "fine - yaxshi",
    "nice - yaxshi",
    "new - yangi",
    "again - yana",
    "believe - ishonmoq",
    "find - topmoq",
    "actually - aslida",
    "even - hatto",
    "hear - eshitmoq",
    "kind of - turdagi",
    "ask - so'ramoq",
    "year - yil",
    "keep - saqlamoq",
    "start - boshlamoq",
    "kid - bolakay",
    "meet - uchratmoq",
    "use - foydalanmoq",
    "help - yordam bermoq",
    "guess - taxmin qilmoq",
    "listen - tinglamoq",
    "bad - yomon",
    "together - birga",
    "better - yaxshiroq",
    "always - doim",
    "place - joy",
    "sure - ha",
    "fun - maroqli",
    "stuff - narsa",
    "party - bazm",
    "best - eng zo'r",
    "remember - eslamoq",
    "look at - qaramoq",
    "job - kasb; ish",
    "room - xona",
    "other - boshqa",
    "only - faqat",
    "name - ism",
    "pretty - chiroyli",
    "tonight - bugun kechqurun",
    "late - kech",
    "date - uchrashuv",
    "today - bugun",
    "wrong - noto'g'ri",
    "stay - qolmoq",
    "phone - telefon (qilmoq)",
    "laugh - kulmoq",
    "old - eski;qari",
    "funny - kulgili",
    "crazy - aqldan ozgan;bema'ni",
    "another - boshqa",
    "problem - muammo",
    "forget - unutmoq",
    "cool - sovuq; zo'r",
    "whole - butun",
    "door - eshik",
    "eat - yemoq",
    "totally - butunlay",
    "watch - ko'rmoq; soat",
    "probably - ehtimol",
    "move - harakatlanmoq",
    "lose - yo'qotmoq",
    "care - o'ylamoq(g'amxo'rlik); ahamiyat bermoq",
    "hate - yomon ko'rmoq; nafrat",
    "buy - sotib olmoq",
    "hand - qo'l; uzatmoq",
    "game - o'yin",
    "wear - kiymoq",
    "weird - g'alati",
    "wedding - nikoh",
    "sleep - uxlamoq",
    "tomorrow - ertaga",
    "kill - o'ldirmoq",
    "hot - issiq",
    "understand - tushunmoq",
    "week - hafta",
    "excuse - ma'zur tutmoq",
    "head - bosh; yo'l olmoq",
    "stupid - ahmoq(ona)",
    "question - savol(ga tutmoq)",
    "worry - havotir (olmoq)",
    "hour - soat",
    "suppose - deb bilmoq; bo'lishi kerak bo'lmoq",
    "real - haqiqiy",
    "hard - qattiq; qiyin",
    "part - qism",
    "already - allaqachon",
    "dinner - kechki ovqat",
    "die - o'lmoq",
    "ready - tayyor (qilmoq)",
    "hope - umid (qilmoq)",
    "story - hikoya",
    "win - g'alaba qozonmoq",
    "number - miqdor",
    "a lot of - ko'p",
    "long - uzun",
    "anyway - baribir; xullas",
    "show - ko'rsatmoq",
    "seem - tuyulmoq",
    "family - oila",
    "word - so'z",
    "person - odam",
    "miss - sog'inmoq; mo'ljalda adashmoq",
    "pay - to'lamoq",
    "drink - ichmoq",
    "also - shuningdek",
    "apartment - kvartira",
    "month - oy",
    "couple - 2ta, 1 juft",
    "deal - kelishmoq; hal qilmoq",
    "child - bola",
    "sound - tovush",
    "spend - sarflamoq",
    "get out - (tashqariga) chiqmoq",
    "other - boshqa",
    "run - yugurmoq",
    "change - o'zgarish; o'zgartirmoq",
    "world - dunyo",
    "sweet - shirin",
    "school - maktab",
    "throw - otmoq",
    "eye - ko'z",
    "anymore - endi, bundan buyog'iga",
    "ago - avval",
    "exactly - aynan",
    "speak - gapirmoq",
    "sit - o'tirmoq",
    "face - yuz(lashmoq)",
    "break - sindirmoq; tanaffus",
    "plan - reja (qilmoq)",
    "look like - o'xshamoq",
    "sometime - biror vaqt(qachondir)",
    "pick - uzmoq(meva); tanlamoq",
    "true - to'g'ri, rost",
    "point - nuqta; ko'rsatmoq(qo'l bn)",
    "read - o'qimoq",
    "serious - jiddiy",
    "easy - oson",
    "beautiful - chiroyli",
    "realize - tushunib yetmoq",
    "wish - tilamoq; tilak",
    "relationship - munosabat",
    "hurt - ozor yetkazmoq",
    "chance - imkoniyat",
    "send - yubormoq",
    "different - boshqacha, farqli",
    "perfect - zo'r(mukammal)",
    "important - muhim",
    "cute - yoqimtoy",
    "write - yozmoq",
    "matter - masala",
    "picture - rasm",
    "reason - sabab",
    "high - baland, yuqori",
    "food - ovqat",
    "dog - it",
    "lie - yolg'on (gapirmoq); yotmoq",
    "birthday - tug'ilgan kun",
    "check - tekshirmoq",
    "fact - fakt",
    "break up - ajralmoq",
    "hit - urmoq",
    "doctor - shifokor",
    "coffee - kofe",
    "business - biznes",
    "moment - lahza",
    "decide - qaror qilmoq",
    "long - uzun",
    "come in - kirmoq",
    "once - bir marta",
    "movie - kino",
    "parent - ota yoki ona",
    "son - o'g'il",
    "news - yangilik",
    "bed - krovat",
    "promise - va'da (bermoq)",
    "young - yosh",
    "drive - mashina minmoq",
    "book - kitob",
    "paper - qog'oz",
    "get back - qaytmoq",
    "line - chiziq",
    "hair - soch",
    "hold - ushlamoq; o'tkazmoq(tadbir/yig'ilish)",
    "end - yakun (yasamoq)",
    "cry - yig'lamoq; baqirmoq",
    "find out - aniqlamoq",
    "joke - hazil (qilmoq)",
    "dead - o'lgan",
    "home - uy",
    "heart - yurak",
    "feeling - his",
    "fire - olov; ishdan bo'shatmoq",
    "seriously - jiddiy",
    "card - karta",
    "mind - hayol,miya; qarshi bo'lmoq",
    "look for - qidirmoq",
    "luck - omad",
    "come back - qaytib kelmoq",
    "marriage - turmush",
    "ring - uzuk; aylana",
    "glad - hursand",
    "open - ochiq; ochmoq",
    "absolutely - butunlay",
    "at all - umuman",
    "invite - taklif qilmoq",
    "learn - o'rganmoq",
    "excite - zavqlantirmoq",
    "awesome - ajoyib",
    "table - jadval",
    "while - davomida",
    "cat - mushuk",
    "steal - o'g'irlamoq",
    "almost - deyarli",
    "get in - kirmoq",
    "company - kompaniya",
    "finally - nihoyat",
    "at least - kamida",
    "sort of - turdagi",
    "turn - burilmoq, aylanmoq",
    "box - quti",
    "bathroom - yuvinish xonasi",
    "mad - jahli chiqqan; jinni",
    "wonder - hayron bo'lmoq",
    "date - sana; xurmo",
    "soon - tez orada",
    "stand - turmoq",
    "pants - shim",
    "street - ko'cha",
    "gift - sovg'a",
    "finish - tugatmoq",
    "special - o'zgacha, qadrli; maxsus",
    "cut - kesmoq",
    "city - shahar",
    "sick - mazasi yo'q",
    "terrible - juda yomon",
    "message - xabar",
    "save - saqlamoq",
    "team - jamoa",
    "sell - sotmoq",
    "walk - yurmoq; sayr",
    "boss - boshliq",
    "music - musiqa",
    "mistake - xato",
    "dream - orzu (qilmoq); tush (ko'rmoq)",
    "foot - oyoq",
    "trust - ishonch; ishonmoq",
    "catch - tutmoq",
    "touch - tegmoq",
    "lunch - tushlik",
    "amazing - ajoyib",
    "key - kalit; muhim",
    "small - kichkina",
    "a little bit - biroz",
    "teach - o'rgatmoq",
    "alone - yolg'iz",
    "stick - tiqmoq; kaltak",
    "enjoy - rohatlanmoq",
    "police - politsiya",
    "scare - qo'rqitmoq",
    "free - erkin; tekin",
    "side - yon(ini olmoq); tomon",
    "definitely - albatta",
    "rest - dam (olmoq); qolgani",
    "truth - haqiqat",
    "become - bo'lmoq (keyinchalik)",
    "half - yarim",
    "set - o'rnatmoq",
    "sound - tovush",
    "bear - ayiq; chidamoq",
    "come up - yoniga bormoq",
    "body - tana",
    "ticket - chipta",
    "surprise - hayrat(lantirmoq); surpriz",
    "secret - sir",
    "college - kollej",
    "smell - hid(lamoq)",
    "song - qo'shiq",
    "dress - ko'ylak; kiyintirmoq",
    "afraid - qo'rqqan",
    "huge - katta",
    "pick up - ko'tarmoq; mashinada olib ketmoq",
    "bag - sumka",
    "bet - pul tikmoq",
    "favourite - sevimli",
    "hard - qattiq; qiyin",
    "rule - qonun-qoida; qaror chiqarmoq",
    "drink - ichmoq; ichimlik",
    "shoot - otmoq",
    "help - yordam (bermoq)",
    "fault - xato",
    "class - dars",
    "hang out - birga vaqt o'tkazmoq",
    "water - suv; sug'ormoq",
    "obviously - aniqki; ochiq-oydin",
    "shoe - oyoq kiyim",
    "ahead - oldinda",
    "raise - ko'tarmoq",
    "upset - xafa (qilmoq)",
    "hold on - to'xtab tur",
    "hospital - shifoxona",
    "machine - mashina(qurilma)",
    "move in - ko'chib kirmoq",
    "single - bitta; yolg'iz",
    "seat - o'rindiq",
    "sense - sezgi, his",
    "weekend - hafta oxiri",
    "able - qila oladigan",
    "someone - kimdir",
    "miss - sog'inmoq",
    "ball - koptok",
    "quit - chiqmoq; odat tashlamoq; taslim bo'lmoq",
    "clothes - kiyim",
    "group - guruh(lamoq)",
    "expect - kutmoq",
    "store - magazin; saqlamoq",
    "dance - raqs (tushmoq)(o'ynamoq)",
    "play - o'ynamoq",
    "show - ko'rsatmoq; shou",
    "cake - tort",
    "relax - dam olmoq",
    "name - nom(lamoq)",
    "lawyer - advokat",
    "push - itarmoq; itarish",
    "town - shahar",
    "lucky - omadli",
    "buddy - og'ayni",
    "plan - reja(lashtirmoq)",
    "worst - eng yomon",
    "knock - taqillatmoq",
    "throat - tomoq",
    "come over - uyiga kelmoq(kimnidir)",
    "explain - tushuntirmoq",
    "club - klub",
    "idiot - ahmoq",
    "bit - biroz; bo'lak",
    "early - erta",
    "pull - tortmoq; tortish",
    "cup - piyola; kubok",
    "ice - muz",
    "plus - plyus; ustunlik",
    "fight - jang (qilmoq), urush(moq)",
    "smart - aqlli",
    "monkey - maymun",
    "shot - o'q uzish; urunish",
    "hide - yashir(in)moq",
    "come out - chiqmoq",
    "restaurant - restoran",
    "close - yopmoq; yaqin",
    "answer - javob (bermoq)",
    "break - sin(dir)moq; tanaffus",
    "figure - figura; raqamlar; tushunmoq, o'ylamoq",
    "strong - kuchli",
    "top - usti,yuqorisi; top",
    "open - ochmoq; ochiq",
    "swear - qasam ichmoq; haqorat(li so'zlarni ishlatmoq)",
    "act - o'zini tutmoq; rol o'ynamoq",
    "building - bino",
    "thought - o'y",
    "apparently - ma'lum bo'lishicha; ko'rinib turibdiki",
    "worse - yomonroq",
    "kick - tepmoq",
    "sale - sotuv; chegirma",
    "sing - kuylamoq",
    "fair - adolatli",
    "suit - kostyum",
    "fast - tez; ro'za tutmoq",
    "turn out - ma'lum bo'lmoq",
    "tape - audio yozuv; skoch",
    "decision - qaror",
    "welcome - hush kelibsiz; kutib olmoq",
    "divorce - ajrashmoq",
    "wonderful - ajoyib",
    "neighbour - qo'shni",
    "piece - bo'lak",
    "notice - payqamoq, ko'rib qolmoq",
    "chair - stul",
    "appreciate - qadrlamoq",
    "work out - sport bn shug'ullanmoq; ish bermoq",
    "list - ro'yhat(da keltirmoq)",
    "drop - tushirib yubormoq; tushish",
    "smoke - tutun; chekmoq",
    "full - to'liq; to'la",
    "entire - butun, hamma",
    "mouth - og'iz",
    "pass - o'tmoq; uzatmoq; dovon",
    "share - ulashmoq",
    "talk - gaplashmoq",
    "sad - xafa",
    "desk - stol",
    "far - uzoq",
    "close - yaqin",
    "answer - javob",
    "congratulation - tabrik",
    "figure - fly - uchmoq",
    "shower - dush (qilmoq)",
    "cold - sovuq",
    "sign - belgi",
    "clean - toza(lamoq)",
    "trip - kichik sayohat;qatnash",
    "normal - oddiy",
    "ruin - rasvo qilmoq;vayrona (qilmoq)",
    "imagine - tasavvur qilmoq",
    "shut up - ovozini o'chirmoq",
    "tough - qattiq; qiyin",
    "order - buyurtma (bermoq); tartib",
    "fall - yiqilmoq;tushish;kuz",
    "fat - semiz; yog'",
    "chicken - tovuq",
    "pretend - o'zini ...dek tutmoq",
    "busy - band",
    "deserve - arzimoq",
    "aunt - xola",
    "manager - menejer",
    "handle - uddalamoq",
    "meeting - yig'ilish",
    "awful - yomon",
    "very - juda",
    "conversation - suhbat",
    "wake up - uyg'onmoq",
    "trouble - muammo, qiyinchilik",
    "follow - ergashmoq; kuzatib bormoq",
    "extra - ortiqcha",
    "star - yulduz",
    "clear - toza; aniq",
    "ridiculous - bema'ni",
    "beat - urmoq; charchagan",
    "forever - bir umr",
    "offer - taklif (qilmoq)",
    "surprise - hayrat(lanmoq);surpriz",
    "bedroom - uxlash xonasi",
    "audition - kasting(da qatnashmoq)",
    "floor - pol; yer",
    "scene - sahna",
    "in front of - ro'parasida",
    "choice - tanlov",
    "client - klient",
    "owe - qarzi bo'lmoq",
    "light - yengil; yorug'lik, chiroq",
    "test - test (olmoq); tekshirmoq",
    "hat - shapka (shlyapa,kepka)",
    "shirt - ko'ylak",
    "present - hozirgi vaqt; sovg'a; taqdim etmoq",
    "middle - o'rtada",
    "window - deraza",
    "take off - yechmoq; ko'tarilmoq(samolyot);yurib ketmoq(biznes)",
    "ride - minmoq(velosiped,hayvonlar)",
    "hire - ishga olmoq",
    "give up - taslim bo'lmoq",
    "return - qaytmoq",
    "cover - o'ramoq; o'ram",
    "quite - ancha",
    "leg - oyoq",
    "forgive - kechirmoq",
    "sandwich - sendvich",
    "lovely - yoqimli",
    "kitchen - oshxona",
    "agree - kelishmoq; rozi bo'lmoq; fikriga qo'shilmoq",
    "white - oq",
    "bird - qush",
    "rock - tosh",
    "black - qora",
    "dress - ko'ylak; kiyintirmoq",
    "allow - ruxsat bermoq",
    "move on - davom etmoq",
    "end up - oxirida ...-moq",
    "tired - charchagan",
    "twin - egizak",
    "flower - gul",
    "wall - devor",
    "late - kech (qolgan)",
    "mess - tartibsiz holat",
    "fix - to'g'irlamoq, tuzatmoq",
    "horrible - juda yomon",
    "cab - taksi",
    "finger - barmoq",
    "attention - e'tibor",
    "guest - mehmon",
    "choose - tanlamoq",
    "completely - butunlay",
    "dump - tashlab yubormoq",
    "need - ehtiyoj",
    "jealous - hasadgo'y; rashk qilgan",
    "blue - ko'k",
    "milk - sut",
    "quick - tez",
    "get off - suvdan quruq chiqmoq",
    "band - qo'shiqchilar guruhi",
    "note - yozuv",
    "desperate - umidsiz va muhtoj",
    "worth - arziydigan",
    "engaged - unashtirilgan",
    "somewhere - biror yerda",
    "poor - kambag'al",
    "honest - rostgo'y",
    "accept - qabul qilmoq",
    "personal - shaxsiy; qalbga yaqin",
    "fall asleep - uxlab qolmoq",
    "assistant - yordamchi",
    "duck - o'rdak",
    "upstairs - yuqori qavatda",
    "tree - daraxt",
    "actor - aktyor",
    "married - oilali",
    "apologise - uzr so'ramoq",
    "bunch - bir nechta",
    "case - holat",
    "propose - taklif bermoq",
    "brain - miya",
    "consider - o'ylab ko'rmoq; deb bilmoq; hisobga olmoq",
    "outside - tashqarida",
    "boat - qayiq, kema",
    "favor - yordam",
    "show up - kelmoq, qatnashmoq",
    "bill - chek, kvitansiya; kupyura",
    "hug - quchoq(lamoq)",
    "cheat - yolg'on ishlatmoq(testda)",
    "uncle - amaki",
    "red - qizil",
    "excellent - a'lo",
    "count - sanamoq; sanoq",
    "begin - boshlamoq",
    "cream - krem; qaymoq",
    "grab - ushlamoq",
    "get up - turmoq",
    "road - yo'l",
    "join - qo'shilmoq",
    "hall - zal",
    "pack - bir quti ...; joylashtirmoq, o'ramoq",
    "inside - ichkarida",
    "prison - qamoqxona",
    "gun - miltiq",
    "coat - palto",
    "Winter jacket - kurtka",
    "cheese - pishloq",
    "hotel - mehmonxona",
    "come with - bilan kelmoq",
    "interview - intervyu (olmoq)",
    "shop - magazin; ustaxona; xarid qilmoq",
    "human - odam",
    "interest - qiziqish; (qiziqtirmoq)",
    "rid - qutqarmoq",
    "remind - eslatmoq",
    "situation - vaziyat",
    "clearly - aniq",
    "last - so'nggi;o'tgan; davom etmoq",
    "prove - isbotlamoq",
    "memory - xotira",
    "fill - to'ldirmoq",
    "put on - kiymoq",
    "hang - os(il)moq",
    "proud - faxrlangan, mag'rur",
    "borrow - olib turmoq",
    "age - yosh; qarimoq",
    "safe - xavfsiz holatda; seyf",
    "plane - samolyot",
    "usually - odatda",
    "roll - dumalamoq; o'ramoq; o'rama",
    "roommate - xonadosh",
    "air - havo; efirga uzatilmoq",
    "grow up - ulg'aymoq",
    "burn - yonmoq, kuymoq",
    "control - nazorat (qilmoq)",
    "candy - qand, konfet",
    "holiday - ta'til; bayram",
    "treat - davolamoq; muomila qilmoq",
    "straight - to'g'ri",
    "art - san'at",
    "death - o'lim",
    "short - qisqa",
    "chick - jo'ja",
    "mention - aytib o'tmoq",
    "couch - divan",
    "nervous - hayajonlangan, asabiy",
    "law - qonun",
    "interesting - qiziqarli",
    "park - park",
    "unbelievable - ishonib bo'lmas",
    "accident - falokat; tasodif",
    "admit - tan olmoq",
    "sit down - o'tirmoq",
    "cookie - pechenye",
    "plate - tarelka",
    "ugly - xunuk",
    "animal - hayvon",
    "evening - kechqurun",
    "bore - zeriktirmoq",
    "corporate - kompaniyaga oid",
    "angry - jahldor",
    "power - kuch, qudrat",
    "grandmother - buvi",
    "emergency - faqulodda vaziyat",
    "get over - yengib o'tmoq",
    "dark - qorong'u; to'q(rang)",
    "carry - olib yurmoq",
    "bottle - butilka",
    "credit - kredit",
    "color - rang; bo'yamoq",
    "in charge - boshliq, mas'ul",
    "pain - og'riq, azob",
    "cellphone - telefon",
    "career - karyera",
    "incredible - aql bovar qilmas",
    "speech - nutq",
    "comfortable - qulay",
    "simple - oddiy",
    "celebrate - nishonlamoq",
    "come from - dan kelmoq",
    "purse - kichik sumka",
    "cancel - bekor qilmoq",
    "letter - harf; xat",
    "switch - boshqasiga o'zgartirmoq",
    "hungry - och",
    "camera - kamera",
    "twice - ikki marta",
    "possible - mumkin, iloji bor",
    "as long as - ...sa bo'ldi",
    "branch - filial; daraxt shoxi",
    "soul - qalb",
    "alive - tirik",
    "assume - deb o'ylamoq",
    "arm - qo'l; qurollantirmoq",
    "honour - sharaf; ulug'lamoq",
    "slow - sekin(lashmoq)",
    "affair - ish, masala",
    "dirty - kir",
    "neighborhood - mahalla",
    "serve - xizmat qilmoq",
    "adult - voyaga yetgan odam",
    "egg - tuxum",
    "hang up - qo'ng'iroqni yakunlamoq",
    "bother - bezovta qilmoq",
    "crush - ezib maydalamoq",
    "information - ma'lumot",
    "get into - (sohaga) kirmoq",
    "cook - pishirmoq; oshpaz",
    "birth - tug'ilish",
    "lead - yo'l boshlamoq; sabab bo'lmoq",
    "jump - sakramoq; sakrash",
    "order - buyruq/buyurtma (bermoq)",
    "grow - o'smoq",
    "future - kelajak",
    "copy - nusxa(sini ko'chirmoq)",
    "cheer - qo'llab-quvvatlamoq(muhlis)",
    "flight - parvoz",
    "difference - farq",
    "sign - belgi; imzo qo'ymoq",
    "afternoon - tushdan keyingi vaqt",
    "state - holat; davlat",
    "deal with - hal qilmoq",
    "ground - yer; ko'chaga chiqishni taqiqlamoq; asos",
    "blame - ayb(lamoq)",
    "prepare - tayyorlamoq",
    "history - tarix",
    "step - qadam (bosmoq); bosqich",
    "left - chap; qolgan",
    "make up for - o'rnini to'ldirish uchun nimadir qilmoq",
    "ask for - so'ramoq(savol emas)",
    "front - oldi",
    "juice - sok",
    "awkward - noqulay(holat)",
    "advice - maslahat",
    "type - tur; klaviaturada yozmoq",
    "drug - dori",
    "anywhere - istalgan joyda",
    "king - qirol",
    "country - davlat",
    "judge - hukm chiqarmoq; sudya",
    "protect - himoya qilmoq",
    "bride - kelin",
    "tooth - tish",
    "fantastic - fantastik",
    "speaker - karnay",
    "buck - 1 dollar",
    "cop - politsiyachi",
    "fan - ventilyator; fanat",
    "cause - sabab (bo'lmoq)",
    "stop - to'xta(t)moq",
    "pie - pirog",
    "involve - iborat bo'lmoq",
    "visit - tashrif (buyurmoq)",
    "smile - jilmaymoq",
    "nurse - hamshira",
    "discuss - muhokama qilmoq",
    "embarrass - uyaltirmoq",
    "fish - baliq",
    "waitress - ofitsiant",
    "stare - tikilib qaramoq",
    "issue - muammo",
    "meat - go'sht",
    "certainly - albatta",
    "beg - o'tinib so'ramoq",
    "camp - lager",
    "careful - ehtiyot",
    "system - sistema",
    "tip - uchi; choychaqa",
    "page - bet, sahifa",
    "taste - ta'm; tatib ko'rmoq; did",
    "guilty - aybdor",
    "lesson - dars",
    "lately - so'ngi paytlarda",
    "believe in - ishonmoq",
    "summer - yoz",
    "suddenly - to'satdan",
    "security - xavfsizlik (xodimlari)",
    "service - xizmat, servis",
    "fast - tez; ro'za tutmoq",
    "grade - baho (qo'ymoq)",
    "charity - hayriya",
    "especially - ayniqsa",
    "certain - ayrim; ishonchi komil",
    "noise - tovush",
    "area - hudud",
    "start - boshlamoq; boshlanish",
    "nose - burun",
    "breakfast - nonushta",
    "scream - baqirmoq; baqirish",
    "draw - chizmoq",
    "housewife - uy bekasi",
    "scary - qo'rqinchi",
    "shut - yopmoq",
    "experience - tajriba",
    "character - xarakter",
    "kind - yaxshi (inson)",
    "glass - shisha, oyna",
    "previously - avval",
    "record - rekord; yozib olmoq(ovoz)",
    "student - o'quvchi",
    "accent - aksent",
    "beep - signal (chalmoq)",
    "tiny - kichkina",
    "lock - qulf(lamoq)",
    "nut - yong'oq",
    "walk - yurmoq; sayr",
    "costume - tarixiy kiyim",
    "turkey - kurka",
    "be all set - tayyor",
    "watch - soat",
    "chocolate - shokolat",
    "someone - kimdir",
    "blood - qon",
    "bowl - chinni, kosa",
    "shame - uyat; uyatga qo'ymoq",
    "sport - sport",
    "quiet - tinch",
    "museum - muzey",
    "delicious - mazali",
    "continue - davom etmoq",
    "truck - yuk mashina",
    "breathe - nafas olmoq",
    "toy - o'yinchoq",
    "conference - konferensiya",
    "paint - bo'yamoq; bo'yoq",
    "airport - aeroport",
    "chef - oshpaz",
    "partner - sherik",
    "toast - tost(non)",
    "insane - jinni",
    "come down - pastga tushmoq",
    "agent - agent",
    "run into - uchratib qolmoq",
    "space - kosmos; joy",
    "transcript - tekst",
    "bottom - tub",
    "total - umumiy",
    "department - bo'lim",
    "regular - muntazam; oddiy",
    "insurance - sug'urta",
    "salad - salat",
    "lots of - ko'p",
    "cousin - amakivachcha",
    "loser - omadsiz",
    "tea - choy",
    "hang on - to'xtab turmoq",
    "hole - teshik",
    "force - kuch; majburlamoq",
    "expensive - qimmat",
    "get away - qochib qutulmoq",
    "roof - tom",
    "respect - hurmat",
    "uncomfortable - noqulay",
    "in case - ...mumkinligi uchun",
    "whisper - pichirlamoq",
    "convince - ishontirmoq",
    "walk in - kirmoq",
    "customer - xaridor",
    "regional - mintaqaviy",
    "account - akkount; tafsilot",
    "matter - masala; modda",
    "giant - katta",
    "mail - pochta xati (yubormoq)",
    "hero - qahramon",
    "commitment - qilinadigan ish; mas'uliyat",
    "move out - ko'chib chiqish",
    "pass away - vafot etmoq",
    "disgusting - jirkanch",
    "low - past",
    "anniversary - yubiley",
    "deep - chuqur",
    "jacket - pidjak",
    "support - qo'llab-quvvatlamoq;",
    "beach - sohil",
    "afford - qurbi yetmoq",
    "van - kichik yuk mashinasi",
    "bachelor - bakalavr; bo'ydoq",
    "model - model; modellashtirmoq",
    "pool - hovuz",
    "lip - lab",
    "come by - birozga kelib ketmoq",
    "pleasure - rohat, zavq",
    "barely - zo'rg'a",
    "feed - oziqlantirmoq",
    "market - bozor; reklama qilmoq",
    "focus - to'liq e'tibor qaratmoq;fokus",
    "oven - pech",
    "form - shakllantirmoq; forma",
    "as well - ham",
    "waste - isrof (qilmoq); chiqindi",
    "pop - yormoq(shar)",
    "honestly - rosti",
    "rude - qo'pol",
    "magazine - jurnal",
    "rich - boy",
    "vacation - ta'til",
    "grandma - buvi",
    "toilet - hojatxona",
    "ear - quloq",
    "open up - dardini aytmoq",
    "suggest - taklif bermoq",
    "spot - nuqta; joy; ko'rmoq",
    "corner - burchak",
    "merry - xursand",
    "cost - narx (turmoq); tushmoq(narxga)",
    "silly - ahmoq",
    "teacher - o'qituvchi",
    "price - narx (qo'ymoq)",
    "captain - kapitan(lik qilmoq)",
    "can - konserva",
    "apology - uzr",
    "court - sud; maydon",
    "professor - professor, o'qituvchi",
    "private - shaxsiy",
    "gross - jirkanch",
    "introduce - tanishtirmoq",
    "responsibility - mas'uliyat",
    "complicate - qiyinlashtirmoq",
    "calm down - jaxlidan tushmoq",
    "bell - qo'ng'iroq",
    "instead of - o'rniga",
    "no longer - ortiq",
    "stranger - begona odam",
    "fake - soxta",
    "fresh - svejiy; chuchuk",
    "swing - tebranmoq",
    "quickly - tez",
    "candle - sham",
    "funeral - dafn marosimi",
    "score - hisob; ball qo'lga kiritmoq",
    "detail - detal",
    "own - egalik qilmoq",
    "actual - aktual; asl",
    "dare - jur'at qilmoq",
    "size - o'lcham",
    "downstairs - pastki qavatda",
    "level - bosqich, daraja",
    "impossible - imkonsiz, iloji yo'q",
    "honeymoon - asal oyi",
    "closet - shkaf",
    "basket - savat",
    "loud - baland (ovoz)",
    "discover - kashf etmoq; aniqlamoq",
    "war - urush",
    "architect - arxitektor",
    "yell - baqirmoq",
    "sauce - sous",
    "dessert - desert",
    "crime - jinoyat",
    "flip - ag'darmoq",
    "build - qurmoq",
    "use - foydalanish; joydalanmoq",
    "mood - kayfiyat",
    "fridge - xolodilnik",
    "willing - xohlaydi",
    "perhaps - balki",
    "friendship - do'stlik",
    "control - (nazorat) qilmoq",
    "sneak - sezdirmasan bormoq",
    "nanny - enaga",
    "package - o'ram, upakovka",
    "living - tirik",
    "slap - tarsaki (urmoq)",
    "sock - paypoq",
    "appointment - uchrashuv(qabul)",
    "potato - kartoshka",
    "wrong - noto'g'ri",
    "trick - xiyla",
    "cash - naqd pul",
    "fit - mos kelmoq; sog'lom",
    "dumb - ahmoq",
    "at first - boshida",
    "award - mukofot",
    "soap opera - serial",
    "director - direktor",
    "email - email (yubormoq)",
    "rough - qattiq; g'adir-budur",
    "bite - tishlamoq",
    "smile - jilmaymoq",
    "theory - teoriya",
    "near - yaqin",
    "attack - hujum (qilmoq)",
    "difficult - qiyin",
    "often - tez-tez",
    "arrest - qamoqqa olmoq",
    "fail - muvaffaqiyatsizlikka uchramoq",
    "clear - tozalamoq",
    "past - o'tmish",
    "field - dala; maydon",
    "gas - gaz",
    "wrap - o'ramoq",
    "destroy - buzib tashlamoq",
    "trash - chiqindi",
    "position - o'rin; lavozim",
    "mall - savdo markazi",
    "button - tugma, knopka",
    "split - bo'lmoq",
    "tall - baland",
    "calm - hotirjam",
    "slip - sirpanib ketmoq",
    "park - park; mashinani qo'ymoq",
    "engagement - unashtiruv",
    "guitar - gitara",
    "instead - o'rniga",
    "include - o'z ichiga olmoq",
    "famous - mashhur",
    "sheet - varoq",
    "terrific - zo'r",
    "gym - zal",
    "cross - kesib o'tmoq",
    "meal - ovqat",
    "future - kelajak",
    "professional - professional",
    "annoying - jahlni chiqaradigan",
    "prefer - afzal ko'rmoq",
    "ship - kema; yukni yubormoq",
    "perfectly - mukammal tarzda",
    "bus - avtobus",
    "player - o‘yinchi, ijrochi",
    "sleep - uyqu",
    "gold - oltin",
    "everywhere - hamma joyda, har yerda",
    "script - matn, ssenariy, qo‘lyozma",
    "drawer - tortma",
    "shake - silkitmoq, qaltiramoq, chayqamoq",
    "photo - rasm, surat, fotosurat",
    "race - poyga, irq",
    "empty - bo‘sh, huvillagan",
    "health - sog‘lik, salomatlik",
    "available - mavjud, tayyor,",
    "lawn - maysazor, gazon",
    "bank - bank, qirg‘oq",
    "possibly - ehtimol, balki",
    "shout - baqirmoq, qichqirmoq",
    "apart - alohida, uzoqda, ajratilgan",
    "tongue - til",
    "run out - tugamoq, qolmaslik",
    "major - asosiy, katta, muhim",
    "earth - yer, tuproq",
    "commit - sodir etmoq, qilmoq",
    "mix - aralashtirmoq, qo‘shmoq",
    "file - fayl, jild",
    "lighting - yoritish, chaqmoq",
    "belt - kamar, belbog‘",
    "pressure - bosim, siquv",
    "pig - cho‘chqa",
    "as soon as - iloji boricha tez, darhol",
    "stand up - turmoq, tik turmoq",
    "bath - vanna, cho‘milish",
    "truly - chinakamiga, haqiqatdan",
    "nail - tirnoq, mix",
    "dinosaur - dinozavr",
    "option - tanlov, variant",
    "invitation - taklifnoma, chaqiruv",
    "swim - suzmoq",
    "fancy - dabdabali, o‘ziga xos, xohlamoq",
    "warehouse - ombor, omborxona",
    "quality - sifat",
    "nowhere - hech qayerda",
    "belong - tegishli bo‘lmoq, mansub bo‘lmoq",
    "midnight - yarim tun",
    "large - katta, ulkan",
    "skin - teri, po‘stloq",
    "healthy - sog‘lom",
    "soup - sho‘rva",
    "toe - barmoq (oyoqda)",
    "wash - yuvmoq",
    "quarter - chorak, to‘rtinchi qism",
    "final - so‘nggi, oxirgi",
    "settle - hal qilmoq, joylashmoq",
    "wild - yovvoyi, vahshiy",
    "maid - xizmatchi, xizmatkor qiz",
    "jail - qamoqxona",
    "judge - hakam, sudya",
    "punish - jazolamoq",
    "boot - etik",
    "clock - soat",
    "neck - bo‘yin",
    "climb - tirmashmoq, chiqmoq",
    "further - yanada, keyingi",
    "mate - sherik, do‘st",
    "church - cherkov",
    "concern - tashvish, qiziqish",
    "gorgeous - go‘zal, betakror",
    "fear - qo‘rquv",
    "add - qo‘shmoq",
    "train - poezd, mashq qilmoq",
    "opportunity - imkoniyat",
    "stomach - qorin",
    "crowd - olomon",
    "impression - taassurot",
    "walk out - chiqib ketmoq",
    "coffeehouse - qahvaxona",
    "tie - galstuk, bog‘lamoq",
    "occur - sodir bo‘lmoq",
    "report - hisobot, xabar bermoq",
    "practice - amaliyot, mashq",
    "pocket - cho‘ntak",
    "towel - sochiq",
    "grab - ushlamoq, tortib olmoq",
    "attractive - jozibador, maftunkor",
    "nap - mizg‘ib olmoq",
    "capable - qobiliyatli, uddaburon",
    "look forward - orziqib kutmoq",
    "punch - musht tushirmoq, zarba bermoq",
    "obvious - aniq, ravshan",
    "island - orol",
    "rain - yomg‘ir",
    "contact - aloqada bo‘lmoq, tegmoq",
    "public - ommaviy, jamoatchilik",
    "winner - g‘olib",
    "little - kichik, oz",
    "bear - ayiq, ko‘tarmoq, bardosh bermoq",
    "schedule - jadval, reja",
    "garbage - axlat, chiqindi",
    "champagne - shampan vinosi",
    "science - ilm, fan",
    "tight - siqilgan, mahkam",
    "breath - nafas",
    "block - blok, to‘siq, to‘smoq",
    "check out - tekshirmoq, chiqib ketmoq",
    "rip - yirtmoq",
    "project - loyiha",
    "pink - pushti",
    "cigarette - sigaret",
    "tattoo - tatuirovka",
    "unfortunately - afsuski",
    "fashion - moda, uslub",
    "lead - boshqarmoq, yo‘lboshchilik qilmoq",
    "suffer - azoblanmoq",
    "ceremony - marosim",
    "lay - yotqizmoq",
    "reach - yetmoq, yetib kelmoq",
    "language - til",
    "straight - to‘g‘ri",
    "from now on - endi, shu kundan boshlab",
    "run away - qochib ketmoq",
    "rat - kalamush",
    "board - taxta, kemaga chiqmoq",
    "medical - tibbiy",
    "horse - ot",
    "presentation - taqdimot",
    "confuse - adashtirmoq, chalkashtirmoq",
    "surgery - jarrohlik",
    "soda - gazli ichimlik",
    "piano - pianino",
    "stick - tayoq; yopishtirmoq",
    "officer - ofitser, amaldor",
    "crack - yoriq, yorilmoq",
    "butter - sariyog‘",
    "shave - soqol olmoq",
    "princess - malika",
    "trade - savdo, savdo qilmoq",
    "complete - to‘liq, tugatmoq",
    "spirit - ruh, ruhiyat",
    "beauty - go‘zallik",
    "bread - non",
    "deliver - yetkazib bermoq",
    "session - sessiya, yig‘ilish",
    "warn - ogohlantirmoq",
    "recognize - tanimoq, anglamoq",
    "enter - kirib kelmoq",
    "move - harakat qilmoq, ko‘chmoq",
    "technically - texnik jihatdan",
    "get along - kelishmoq, til topishmoq",
    "suicide - o‘z joniga qasd qilish",
    "terms - shartlar",
    "tone - ohang",
    "turn around - o‘girilib qaramoq, burilmoq",
    "since - beri; chunki",
    "evil - yomonlik; shaytoniylik",
    "apple - olma",
    "excuse - bahona; kechirmoq",
    "brave - jasur; mard",
    "incredibly - hayratlanarli darajada; nihoyatda",
    "pillow - yostiq",
    "threaten - tahdid qilmoq",
    "fruit - meva; natija",
    "muffin - keks, bulka",
    "style - uslub; moda",
    "lobster - dengiz qisqichbaqasi",
    "exact - aniq; to‘liq",
    "pound - funt (og‘irlik yoki valyuta); ezmoq",
    "dangerous - xavfli",
    "drum - baraban; bochka",
    "liar - yolg‘onchi",
    "farm - ferma; qishloq xo‘jaligi yerlari",
    "robot - robot",
    "detective - detektiv; tergovchi",
    "signal - signal; ishora",
    "rent - ijara; ijaraga olmoq",
    "pathetic - ayanchli; o‘tkinchi",
    "sob - ingrab yig‘lamoq",
    "steak - bifshteks",
    "officially - rasmiy tarzda",
    "pumpkin - qovoq",
    "somehow - qandaydir tarzda",
    "subway - metro; yer osti yo‘li",
    "code - kod; qoidalar majmuasi",
    "yard - hovli; uzunlik o‘lchovi",
    "throw up - qusmoq; tashlab yubormoq",
    "glasses - ko‘zoynak",
    "selfish - o‘zini o‘ylaydigan",
    "avoid - chetlab o‘tmoq; qochmoq",
    "press - matbuot; bosmoq",
    "wind - shamol; aylantirmoq",
    "attract - jalb qilmoq",
    "abandon - tark etmoq; voz kechmoq",
    "hurry (up) - shoshilmoq; tezlashtirmoq",
    "sun - quyosh",
    "puppy - kuchukcha",
    "waiter - ofitsiant",
    "casual - oddiy; tasodifiy",
    "travel - sayohat qilmoq",
    "complain - shikoyat qilmoq",
    "interrupt - bo‘lmoq; gapni bo‘lmoq",
    "get through - muvaffaqiyatli tugatmoq; aloqaga chiqmoq",
    "present - sovg‘a; hozirgi; taqdim qilmoq",
    "theme - mavzu",
    "generous - saxiy; bag‘rikeng",
    "look out - ehtiyot bo‘lmoq; qaramoq",
    "opinion - fikr; qarash",
    "all of a sudden - kutilmaganda",
    "double - ikki hissa; ikki barobar",
    "kind - xushmuomala; tur",
    "bright - yorqin; aqlli",
    "strange - g‘alati; notanish",
    "dentist - tish shifokori",
    "friendly - do‘stona",
    "perform - ijro etmoq; amalga",
    "plenty - ko‘p; mo‘l-ko‘l",
    "spring - bahor; buloq",
    "sweater - jemper",
    "refuse - rad etmoq; chiqindi",
    "string - ip; qator",
    "survive - omon qolmoq",
    "license - litsenziya; ruxsatnoma",
    "receive - qabul qilmoq",
    "search - qidiruv; qidirmoq",
    "event - hodisa; voqea",
    "slap - tarsaki; urmoq",
    "murder - qotillik; o‘ldirmoq",
    "strike - zarba; ish tashlamoq",
    "dress up - bezanmoq; kiyinish",
    "depress - tushkunlikka tushirmoq",
    "popular - mashhur; ommabop",
    "bone - suyak",
    "rock - tosh; tebranmoq",
    "touch - tegmoq; ta’sir qilmoq",
    "distance - masofa; uzoqlik",
    "folk - xalq; odamlar",
    "walk away - ketib qolmoq; uzoqlashmoq",
    "by now - hozirgacha",
    "hit on - gap otmoq; o‘ylab topmoq",
    "turn into - aylantirmoq; o‘zgarmoq",
    "please - iltimos; rozi qilmoq",
    "pair - juft; juftlamoq",
    "circle - doira; aylanmoq",
    "lamp - chiroq",
    "interest - qiziqish; foyda",
    "ghost - arvoh; ruh",
    "adorable - yoqimli; jozibador",
    "figure out - tushunmoq; hal qilmoq",
    "adopt - farzandlikka olmoq; qabul",
    "lord - xo‘jayin; oliyjanob",
    "opera - opera",
    "inappropriate - noqulay; noo‘rin",
    "official - rasmiy; mansabdor",
    "brunch - erta tushlik",
    "point - nuqta; ko‘rsatmoq",
    "magic - sehr; mo‘jiza",
    "past - o‘tmish; o‘tgan",
    "sugar - shakar; qand",
    "smoke - tutun; chekish",
    "killer - qotil",
    "doubt - shubha; gumon",
    "due - kerakli; muayyan vaqtda",
    "spin - aylantirmoq; aylanish",
    "suggestion - taklif; maslahat",
    "wing - qanot",
    "salesman - sotuvchi",
    "positive - ijobiy; ishonchli",
    "phase - bosqich",
    "drag - sudramoq; tortmoq",
    "suit - kostyum; mos kelmoq",
    "familiar - tanish; bilgan",
    "coma - koma",
    "knee - tizza",
    "pet - uy hayvoni; erkalamoq",
    "bridge - ko‘prik",
    "cheap - arzon",
    "lunch - tushlik",
    "slide - sirpanmoq; siljimoq",
    "labor - mehnat; tug‘ruq",
    "natural - tabiiy; oddiy",
    "pack - o‘ramoq; qadoqlamoq",
    "replace - almashtirmoq; o‘rnini bosmoq",
    "agency - agentlik; idora",
    "makeup - pardoz; tuzilma",
    "reservation - bron qilish; shubha",
    "nature - tabiat; xususiyat",
    "peace - tinchlik; xotirjamlik",
    "laundry - kir yuvish; kir yuviladigan joy",
    "mature - yetuk; pishgan",
    "earn - topmoq; ishlamoq",
    "volunteer - ko‘ngilli; ko‘ngilli bo‘lmoq",
    "innocent - aybsiz; begunoh",
    "prize - sovrin; mukofot",
    "employee - xodim; ishchi",
    "passion - ehtiros; qiziqish",
    "shout - baqirmoq; qichqirmoq",
    "catch up - yetib olmoq; tutib olmoq",
    "create - yaratmoq",
    "pen - ruchka; qalam",
    "pancake - quymoq",
    "ankle - to‘piq",
    "half - yarmi; bo‘lak",
    "impress - ta’sir qilmoq",
    "snack - tamaddi; yengil ovqat",
    "get down - pastga tushmoq; tushunmoq",
    "weight - vazn",
    "curious - qiziquvchan; ajablanarli",
    "unfair - adolatsiz",
    "safety - xavfsizlik",
    "blind - ko‘r; to‘sib qo‘ymoq",
    "worker - ishchi; mehnatkash",
    "rub - ishqalamoq; artmoq",
    "spit - tupurmoq; tupuk",
    "charge - to‘lov; ayblov",
    "jewelry - taqinchoq",
    "skip - o‘tkazib yubormoq",
    "gather - yig‘moq; yig‘ilmoq",
    "operation - operatsiya; faoliyat",
    "set up - o‘rnatmoq; tashkil qilmoq",
    "universe - koinot",
    "committee - qo‘mita",
    "permission - ruxsat",
    "supportive - qo'llab-quvvatlaydigan",
    "concert - kontsert",
    "put in - qo‘shmoq; joylashtirmoq",
    "property - mulk; xususiyat",
    "regret - afsuslanmoq; pushaymon",
    "commercial - tijoriy; reklama",
    "unhappy - baxtsiz; norozilik holati",
    "film - film; plyonka",
    "address - manzil; murojaat",
    "impressive - ta'sirli; hayratlanarli",
    "turn on - yoqmoq",
    "tie - galstuk; bog‘lamoq",
    "original - asl; o‘ziga xos",
    "mark - belgi; baho; belgilamoq",
    "attack - hujum; hujum qilmoq",
    "member - a’zo",
    "several - bir necha",
    "bury - ko‘mmoq",
    "precious - qimmatli; aziz",
    "walk - yurmoq; sayr",
    "around - atrofida; taxminan",
    "soft - yumshoq",
    "tool - asbob; vosita",
    "otherwise - aks holda; boshqacha",
    "male - erkak; erkak jinsli",
    "lick - yalamoq",
    "recently - yaqinda",
    "nightmare - dahshatli tush; qo‘rqinchli holat",
    "badly - yomon; og‘ir",
    "miracle - mo‘jiza",
    "grant - ajratmoq; taqdim qilmoq",
    "murder - qotillik; o‘ldirmoq",
    "ignore - e’tiborsiz qoldirmoq",
    "president - prezident",
    "dish - idish; taom",
    "accidentally - tasodifan",
    "sight - ko‘rish; manzara",
    "bat - yarasa; tayoq",
    "allergic - allergiyali",
    "lonely - yolg‘iz; tashlandiq",
    "describe - tasvirlamoq; ifodalamoq",
    "delivery - yetkazib berish",
    "recipe - retsept",
    "bake - pishirmoq (non, pirog va boshqalar)",
    "baseball - beysbol",
    "social - ijtimoiy",
    "driver - haydovchi",
    "lift - ko‘tarmoq; lift",
    "forbid - taqiqlamoq",
    "stink - sasimoq",
    "disappear - g‘oyib bo‘lmoq",
    "ton - tonna; juda ko‘p miqdor",
    "competition - musobaqa; raqobat",
    "solve - yechmoq; hal qilmoq",
    "determine - aniqlamoq; belgilamoq",
    "garage - garaj",
    "monster - maxluq",
    "audience - tomoshabinlar; tinglovchilar",
    "legal - qonuniy",
    "transfer - o‘tkazmoq; ko‘chirmoq",
    "chain - zanjir; tizim",
    "county - graflik",
    "library - kutubxona",
    "eventually - oxir-oqibat",
    "classic - klassik",
    "fella - yigit; do‘st",
    "test - test; sinov",
    "tour - sayohat; gastrol",
    "exhausted - holdan toygan; charchagan",
    "turtle - toshbaqa",
    "tradition - an’ana",
    "image - tasvir; obraz",
    "compare - solishtirmoq",
    "salt - tuz",
    "fold - buklamoq; qatlam",
    "wet - nam; ho‘l",
    "program - dastur; reja",
    "happiness - baxt; quvonch",
    "opposite - qarama-qarshi; qarshisida",
    "escape - qochmoq; qutilmoq",
    "stair - zina; qadam",
    "bike - velosiped; mototsikl",
    "heavy - og‘ir; jiddiy",
    "alarm - signal; xavotir",
    "challenge - chaqiriq; qiyinchilik",
    "patch - latta; yamamoq",
    "report - hisobot; xabar bermoq",
    "bee - asalari",
    "tear - ko‘z yoshi; yirtmoq",
    "necessary - zarur; muhim",
    "wheel - g‘ildirak",
    "promise - va’da; va’da bermoq",
    "mile - mil",
    "sync - sinxronlashmoq",
    "gum - milk; saqich",
    "pill - dori tabletkasi",
    "blond - sariqsoch; sarg‘ish",
    "tear - yirtmoq; ko‘z yoshi",
    "poster - plakat",
    "light - yorug‘lik; yengil; yoqmoq",
    "odd - g‘alati; toq son",
    "contest - tanlov; musobaqa",
    "roll - dumalamoq; rolik",
    "deny - rad etmoq",
    "incident - hodisa",
    "laugh - kulmoq",
    "heat - issiqlik; qizdirmoq",
    "illegal - noqonuniy",
    "outfit - kiyim-kechak",
    "wave - to‘lqin; qo‘l silkitmoq",
    "orange - apelsin; to‘q sariq rang",
    "literally - so‘zma-so‘z; haqiqatan ham",
    "respect - hurmat; hurmat qilmoq",
    "miserable - ayanchli; baxtsiz",
    "poison - zahar; zaharlamoq",
    "disappoint - hafsalasini pir qilmoq",
    "elevator - lift",
    "patient - sabrli; bemor",
    "apologize - kechirim so‘ramoq",
    "cookie - pechenye",
    "engine - motor; dvigatel",
    "hilarious - kulgili; qiziq",
    "period - davr; muddat",
    "season - fasl; mavsum",
    "beef - mol go‘shti",
    "insist - talab qilmoq; turib olmoq",
    "solid - qattiq; mustahkam",
    "groom - kuyov; parvarish qilmoq",
    "centre - markaz",
    "plumber - santexnik",
    "evidence - dalil; isbot",
    "zoo - hayvonot bog‘i",
    "sea - dengiz",
    "whistle - hushtak; hushtak chalmoq",
    "joy - quvonch",
    "depression - tushkunlik",
    "cover - qoplamoq; qoplama",
    "process - jarayon; qayta ishlamoq",
    "row - qator; urushmoq",
    "purpose - maqsad",
    "study - o‘rganmoq; tadqiqot",
    "plastic - plastik; moslashuvchan",
    "promote - targ‘ib qilmoq; lavozim ko‘tarmoq",
    "land - yer; qo‘nmoq",
    "put out - o‘chirmoq; chiqarib qo‘ymoq",
    "remove - olib tashlamoq; chiqarib yubormoq",
    "parade - parad",
    "hip - son; zamonaviy",
    "emotional - hissiy",
    "mirror - oyna",
    "successful - muvaffaqiyatli",
    "firm - mustahkam; kompaniya",
    "support - qo‘llab-quvvatlamoq; yordam",
    "nickname - laqab",
    "nail - tirnoq; mix",
    "annulment - bekor qilish",
    "confession - iqror; tan olish",
    "match - o‘yin; gugurt; mos kelmoq",
    "battle - jang; kurashmoq",
    "release - chiqarib yubormoq; e’lon qilish",
    "take out - olib chiqmoq; chiqarib tashlamoq",
    "hardly - deyarli yo‘q; zo‘rg‘a",
    "provide - ta’minlamoq; yetkazib",
    "though - garchi; baribir",
    "version - versiya; talqin",
    "aisle - yo‘lak",
    "zone - zona; hudud",
    "explanation - tushuntirish",
    "track - yo‘l; iz; kuzatmoq",
    "earring - zirak",
    "victim - qurbon",
    "scientist - olim",
    "hop - sakramoq; otilmoq",
    "explode - portlamoq",
    "dip - botirmoq; sho‘ng‘imoq",
    "awake - uyg‘oq; uyg‘onmoq",
    "balcony - balkon",
    "behavior - xulq-atvor",
    "cook - oshpaz",
    "glove - qo‘lqop",
    "risk - xavf",
    "magical - sehrli",
    "movie - film",
    "tissue - mato; salfetka",
    "repeat - takrorlamoq",
    "run - yugurmoq; ishlamoq",
    "stress - stress; bosim",
    "screen - ekran",
    "television - televizor",
    "tired - charchagan",
    "fantasy - fantaziya",
    "mystery - sir; jumboq",
    "item - buyum; mahsulot",
    "toss - tashlamoq",
    "pick out - tanlab olish",
    "invent - ixtiro qilmoq",
    "on hold - kutishda",
    "visit - tashrif buyurmoq",
    "sadly - afsuslanib",
    "middle - o‘rtada",
    "mouse - sichqon",
    "respond - javob bermoq",
    "connection - ulanish",
    "announcement - e’lon",
    "exist - mavjud bo‘lmoq",
    "lottery - lotereya",
    "central - markaziy",
    "league - liga",
    "temp - vaqtinchalik",
    "refer - murojaat qilmoq; havola qilmoq",
    "furniture - mebel",
    "buzzed - g‘iltillagan; mast",
    "tail - dum",
    "thin - yupqa; oriq",
    "however - ammo; lekin",
    "painful - og‘riqli; azobli",
    "broken - singan; buzilgan",
    "treat - davolamoq; muomala qilmoq",
    "scratch - tirnamoq; tirnalgan joy",
    "announce - e’lon qilmoq",
    "post - xabar; joylashtirmoq",
    "click - bosmoq; shiqillatmoq",
    "pour - quyib yubormoq",
    "spoon - qoshiq",
    "sue - sudga bermoq",
    "hook - ilgak; ilib qo‘ymoq",
    "solution - yechim; eritma",
    "leather - charm",
    "wake - uyg‘onmoq",
    "someday - bir kun",
    "guard - soqchi; qo‘riqlamoq",
    "panties - ichki kiyim (ayollar)",
    "separate - ajratmoq; alohida",
    "condo - ko‘p qavatli uy (bir xonadonli mulk)",
    "crisis - inqiroz",
    "shape - shakl; holat",
    "heaven - jannat; osmonda",
    "laundry - kir yuvish; kir yuviladigan joy",
    "danger - xavf",
    "benefit - foyda; manfaat",
    "homeless - uysiz",
    "search - qidiruv; izlamoq",
    "contract - shartnoma; qisqarmoq",
    "remain - qolmoq; saqlanmoq",
    "rush - shoshmoq; tezlik",
    "routine - odatiy ishlar; tartib",
    "sword - qilich",
    "confident - ishonchli; o‘ziga ishongan",
    "dirt - kir; loy",
    "product - mahsulot",
    "promotion - targ‘ibot; lavozim ko‘tarish",
    "fear - qo‘rquv; qo‘rqmoq",
    "crab - qisqichbaqa",
    "grand - ulug‘vor; katta",
    "giggle - kulimsiramoq; hijolatdan kulmoq",
    "legendary - afsonaviy",
    "look down - mensimaslik; pastga qaramoq",
    "bubble - pufak",
    "have in common - umumiy jihati bo‘lmoq",
    "hand rest - qo‘l dam olish joyi",
    "occasion - vaziyat; imkoniyat",
    "expense - xarajat",
    "view - qarash; manzara",
    "spoil - buzmoq; erkalatib yubormoq",
    "worth - qiymat; arziydi",
    "spill - to‘kib yubormoq",
    "laughter - kulgu",
    "bump - urilish; to‘qnashuv",
    "result - natija; bo‘lmoq",
    "humor - hazil; yumor",
    "mister - janob",
    "come along - qo‘shilmoq; kelib qolmoq",
    "wood - yog‘och; o‘rmon",
    "affect - ta’sir qilmoq",
    "pal - do‘st; og‘ayni",
    "matching - mos; moslashtirilgan",
    "female - ayol; ayol jinsli",
    "rush - shoshilinch; tezlik",
    "apply - murojaat qilmoq; qo‘llamoq",
    "community - jamoa; mahalla",
    "crash - halokat; urilmoq",
    "come into - ichiga kirib kelmoq",
    "appear - ko‘rinmoq; paydo bo‘lmoq",
    "lap - tizzaning usti; aylana",
    "second - ikkinchi; soniya",
    "clown - masxaraboz",
    "get pissed - jahli chiqmoq (so‘zlashuv uslubida)",
    "video - video",
    "offensive - haqoratomuz; hujumkor",
    "policy - siyosat; tartib",
    "t - shirt - futbolka",
    "come off - tushib qolmoq; muvaffaqiyat qozonmoq",
    "brilliant - ajoyib; yorqin",
    "percent - foiz",
    "diamond - olmos",
    "pharmacist - dorixona xodimi",
    "napkin - salfetka",
    "mug - krujka; chashka",
    "blanket - adyol; yopinchiq",
    "tux - smokin (erkaklar rasmiy kiyimi)",
    "look up - yuqoriga qaramoq; yaxshilanishni kutmoq",
    "channel - kanal; yo‘l",
    "management - boshqaruv; rahbariyat",
    "defend - himoya qilmoq",
    "beginning - boshlanish; avval",
    "intend - niyat qilmoq; rejalashtirmoq",
    "disaster - falokat; ofat",
    "file - fayl; hujjat",
    "guess - taxmin qilmoq",
    "helpful - foydali; yordam beradigan",
    "cable - kabel",
    "hate - nafratlanmoq; yoqtirmaslik",
    "book - kitob; bron qilish",
    "basement - podval; yer osti",
    "trust - ishonch; ishonmoq",
    "duty - vazifa; bojxona to‘lovi",
    "strength - kuch; qudrat",
    "hold up - ushlab turmoq; to‘xtatmoq",
    "mental - ruhiy; aqliy",
    "general - umumiy; boshqaruvchi",
    "golf - golf o‘yini",
    "salmon - qizil baliq",
    "tomato - pomidor",
    "advantage - afzallik",
    "lousy - yomon; sifatsiz",
    "hit - urmoq; zarba",
    "pass - o‘tmoq; yo‘llanma",
    "cruise - dengiz sayohati",
    "intense - kuchli; qattiq",
    "bail - garov; qutqarmoq",
    "foreign - xorijiy; chet el",
    "land - yer; qo‘nmoq",
    "hear from - xabar eshitmoq",
    "shy - uyatchan; tortinchoq",
    "negative - salbiy",
    "weak - zaif",
    "poem - she’r",
    "operate - boshqarmoq; operatsiya qilmoq",
    "ironic - kinoyali",
    "jail - qamoqxona",
    "according to - ga ko‘ra",
    "route - yo‘l; marshrut",
    "thumb - bosh barmoq",
    "basketball - basketbol",
    "energy - energiya",
    "argue - bahslashmoq; tortishmoq",
    "knock - taqillatmoq; urmoq",
    "sharp - o‘tkir; keskin",
    "episode - epizod; qism",
    "kick - tepmoq; zarba",
    "environment - atrof-muhit; muhit",
    "counter - peshtaxta; qarshi turmoq",
    "fall - yiqilish; kuz fasli",
    "take away - olib tashlamoq; olib ketmoq",
    "south - janub",
    "carpet - gilam",
    "iron - temir; dazmol",
    "personally - shaxsan; o‘zi",
    "stain - dog‘; dog‘ tushirmoq",
    "hockey - xokkey",
    "tend - moyil bo‘lmoq; g‘amxo‘rlik qilmoq",
    "appropriate - mos; o‘rinli",
    "rash - toshma; shoshqaloqlik",
    "rise - ko‘tarilish; o‘smoq",
    "advertise - reklama qilmoq",
    "suspect - gumon qilmoq; gumondor",
    "hostage - garovdagi odam",
    "downsize - qisqartirmoq",
    "hopefully - umid qilamanki; xudo xohlasa",
    "yellow - sariq",
    "sweep - supurmoq; tozalamoq",
    "diet - parhez; oziq-ovqat tartibi",
    "courage - jasorat",
    "memo - eslatma; qisqa xabar",
    "onion - piyoz",
    "sort of - taxminan; bir xil",
    "possibility - imkoniyat",
    "bald - kal",
    "squeeze - siqmoq; bosmoq",
    "fries - kartoshka fri",
    "ceiling - shift",
    "recommend - tavsiya qilmoq",
    "loose - bo‘sh; erkin",
    "artist - rassom; san’atkor",
    "stage - sahna; bosqich",
    "dial - terish (telefon raqamini)",
    "mustache - mo‘ylov",
    "shoulder - yelka; o‘z bo‘yniga olmoq",
    "research - tadqiqot; o‘rganmoq",
    "freeze - muzlamoq; muzlatmoq",
    "west - g‘arb",
    "reject - rad qilmoq; yoqtirmaslik",
    "neat - ozoda; saranjom",
    "approve - ma’qullamoq; tasdiqlamoq",
    "culture - madaniyat; urf-odat",
    "childhood - bolalik",
    "radio - radio",
    "gesture - imo-ishora; imo bilan ifodalamoq",
    "refrigerator - muzlatgich",
    "talent - iste’dod",
    "angel - farishta",
    "slowly - sekin; asta",
    "lie down - yotmoq",
    "grandpa - bobo (so‘zlashuv uslubida)",
    "look back - orqaga qaramoq; o‘tmishni eslamoq",
    "bike - velosiped",
    "anytime - har qanday vaqtda",
    "anger - g‘azab; jahldorlik",
    "ultimate - yakuniy; eng muhim",
    "bend - egmoq; egilmoq",
    "be based on - asoslangan bo‘lmoq",
    "leave - tark etmoq; ketmoq",
    "cancer - saraton kasalligi",
    "deer - kiyik",
    "concentrate - diqqatni jamlamoq; kontsentratsiya qilmoq",
    "mark - belgi; belgilamoq",
    "physical - jismoniy; fizik",
    "mess up - buzib qo‘ymoq; xatoga yo‘l qo‘ymoq",
    "groceries - oziq-ovqat mahsulotlari",
    "rage - qahr-g‘azab",
    "identical - bir xil",
    "unpack - o‘ramdan chiqarish",
    "differently - boshqacha; farqli tarzda",
    "value - qiymat; qadrlamoq",
    "pitch - maydon; ohang",
    "jeans - jinsi shim",
    "compliment - maqtov; maqtamoq",
    "guilt - aybdorlik; gunohkorlik hissi",
    "classy - zamonaviy; didli",
    "concern - tashvish; qiziqtirmoq",
    "debt - qarz",
    "yoga - yoga",
    "decent - munosib; odobli",
    "enemy - dushman",
    "website - veb-sayt",
    "journey - safar; sayohat",
    "medication - dori; davolash vositasi",
    "creative - ijodiy",
    "olive - zaytun",
    "perk - qo‘shimcha imtiyoz",
    "typical - odatiy; o‘ziga xos",
    "whipped - qamchilangan; urilgan (qaymoq yoki shunga o‘xshash narsalar haqida)",
    "loud - baland (ovoz)",
    "jar - banka",
    "dialogue - muloqot; dialog",
    "gentle - muloyim; yumshoq",
    "yummy - mazali",
    "grape - uzum",
    "on top of - ustida; qo‘shimcha ravishda",
    "behave - o‘zini tutmoq; xulq-atvor",
    "spell - harflab yozmoq; sehr",
    "lasagna - lazanya (makaron taomi)",
    "doughnut - ponchik",
    "mountain - tog‘",
    "remote - uzoq; masofadan boshqariladigan",
    "swallow - yutmoq",
    "coach - murabbiy; avtobus",
    "argument - bahs; dalil",
    "reference - havola; manba",
    "sweat - ter; terlamoq",
    "pipe - quvur",
    "practically - deyarli; amalda",
    "skirt - yubka",
    "tension - taranglik; zo‘riqish",
    "cowboy - kovboy",
    "knife - pichoq",
    "agree with - fikrga qo‘shilmoq",
    "tray - lagan",
    "confess - tan olmoq; e’tirof etmoq",
    "casting - aktyorlar tanlovi",
    "wallet - hamyon",
    "review - ko‘rib chiqish; sharh",
    "darling - jonim; azizim",
    "flatter - laganbardorlik qilmoq",
    "reality - haqiqat",
    "damage - zarar; zarar yetkazmoq",
    "fair - adolatli; yarmarka",
    "tight - tor; siqilgan",
    "design - dizayn; loyihalash",
    "immediately - darhol",
    "doubt - shubha; shubhalanmoq",
    "desert - cho‘l; tark etmoq",
    "place - joy; joylashtirmoq",
    "temporary - vaqtinchalik",
    "hint - ishora; maslahat",
    "murderer - qotil",
    "medicine - dori; tibbiyot",
    "crawl - sudralmoq",
    "panic - vahima; vahimaga tushmoq",
    "stock - zahira; aksiyalar",
    "simply - oddiygina; faqat",
    "common - umumiy; odatiy",
    "coin - tanga; so‘z yaratmoq",
    "mattress - to‘shak",
    "no matter how - qanchalik bo‘lmasin",
    "oil - yog‘; moy",
    "turn off - o‘chirmoq",
    "teenager - o‘smir",
    "proof - dalil; isbot",
    "rare - noyob; kamdan-kam",
    "veil - ro‘mol; pardalamoq",
    "noodle - makaron",
    "look into - o‘rganmoq; tadqiq qilmoq",
    "reception - qabul; ziyofat",
    "square - kvadrat; maydon",
    "salary - oylik maosh",
    "belly - qorin",
    "wish - tilak; tilamoq",
    "crappy - sifatsiz; yomon",
    "adventure - sarguzasht",
    "privacy - shaxsiylik; maxfiylik",
    "forth - oldinga; oldinga tomon",
    "guts - ichaklar; jasorat",
    "label - yorliq; yorliqlamoq",
    "form - shakl; shakllantirmoq",
    "melt - erimoq",
    "quietly - sekin; sokin",
    "beep - g‘iltillash; signal berish",
    "winter - qish",
    "frame - ramka; ramkalamoq",
    "cigar - sigara",
    "water - suv; sug‘ormoq",
    "donate - xayriya qilmoq",
    "tiger - yo‘lbars",
    "traffic - tirbandlik; transport oqimi",
    "share - ulush; bo‘lishmoq",
    "discount - chegirma; chegirmoq",
    "lean - egilmoq; suyangan",
    "disturb - bezovta qilmoq",
    "edge - chekka; qirrasi",
    "represent - ifodalamoq; vakillik",
    "lipstick - lab bo‘yog‘i",
    "speed - tezlik; shoshmoq",
    "beat up - kaltaklamoq",
    "tank - bak; tank",
    "insult - haqorat; haqorat qilmoq",
    "path - yo‘l; so‘qmoq",
    "fancy - dabdabali; yoqtirmoq",
    "live - jonli; yashamoq",
    "load - yuk; yuklamoq",
    "success - muvaffaqiyat",
    "lifetime - hayot davomida; umr",
    "seat - o‘rindiq; joylashtirmoq",
    "hallway - yo‘lak",
    "organize - tashkil qilmoq",
    "category - toifa; sinf",
    "trip - sayohat; qoqilib ketmoq",
    "master - usta; mukammal",
    "pass out - hushidan ketmoq",
    "sickness - kasallik",
    "specific - aniq; o‘ziga xos",
    "betray - xiyonat qilmoq",
    "humiliate - tahqirlamoq",
    "random - tasodifiy",
    "receptionist - qabulxona xodimi",
    "effort - harakat; urinish",
    "host - mezbon; mezbonlik qilmoq",
    "wander - tentirab yurmoq",
    "freezer - muzlatkich",
    "betrayal - xiyonat",
    "passport - pasport",
    "cart - arava",
    "require - talab qilmoq",
    "cocktail - kokteyl",
    "dealer - savdogar; sotuvchi",
    "step up - ko‘tarilmoq; jadallashtirmoq",
    "booze - spirtli ichimlik",
    "painting - surat; rasm",
    "afterwards - keyin; undan so‘ng",
    "spank - tarsaki urmoq",
    "grief - qayg‘u; motam",
    "cheesecake - pishloqli pirog",
    "devastate - vayron qilmoq; xarob qilmoq",
    "kidnap - o‘g‘irlab ketmoq",
    "fund - jamg‘arma; moliyalashtirmoq",
    "grownup - kattalar; balog‘atga yetgan",
    "lab - laboratoriya",
    "picture - surat; tasvir",
    "cranberry - kızılmiya; kızılolma",
    "bust - portlash; byust",
    "pride - g‘urur; mag‘rurlik",
    "wave - to‘lqin; qo‘l silkimoq",
    "vegetarian - vegetarian",
    "be ashamed - uyalmoq",
    "creep out - qo‘rqitmoq; bezovta qilmoq",
    "pile - uyum; yig‘moq",
    "bless - duo qilmoq; barakali qilmoq",
    "trouble - muammo; bezovta qilmoq",
    "come through - o‘tib kelmoq; amalga oshirmoq",
    "opening - ochilish; teshik",
    "latte - latta kofesi",
    "rice - guruch",
    "discussion - muhokama",
    "village - qishloq",
    "banana - banan",
    "justice - adolat",
    "wait up - kutib turmoq",
    "role - rol; vazifa",
    "nephew - jiyan (erkak)",
    "fall down - yiqilib tushmoq",
    "blouse - ko‘ylak (ayollar uchun)",
    "stick with - sodiq qolmoq; birga bo‘lmoq",
    "proposal - taklif; reja",
    "wipe - artmoq; artish",
    "sweaty - terlagan",
    "fate - taqdir",
    "spare - ortiqcha; tejab qolmoq",
    "purple - binafsha rang",
    "cough - yo‘tal; yo‘talmok",
    "react - javob bermoq; reaksiya qilmoq",
    "deed - ish; hujjat",
    "tax - soliq",
    "easily - osonlik bilan",
    "bullet - o‘q (qurolniki)",
    "bucket - chelak",
    "sound - tovush; eshitilmoq",
    "celebration - bayram",
    "relieve - yengillik bermoq",
    "rate - stavka; baholamoq",
    "triplet - uch egizak",
    "lecture - ma’ruza; ma’ruza o‘qimoq",
    "discovery - kashfiyot",
    "qualified - malakali",
    "bonus - mukofot; qo‘shimcha daromad",
    "flyer - varaqa; parvoz qiluvchi",
    "reveal - oshkor qilmoq",
    "title - nom; sarlavha",
    "charming - maftunkor; jozibali",
    "tub - idish; vanna",
    "honor - sharaf; hurmat qilmoq",
    "thrilled - hayajonlangan",
    "relief - yengillik",
    "shock - zarba; hayrat",
    "moron - ahmoq",
    "false - noto‘g‘ri; yolg‘on",
    "flaw - nuqson",
    "exit - chiqish; chiqmoq",
    "donation - xayriya",
    "main - asosiy",
    "base - asos; poydevor",
    "therapist - terapevt",
    "weapon - qurol",
    "break into - buzib kirish; boshlamoq",
    "attend - qatnashmoq; bormoq",
    "in order to - maqsadida; uchun",
    "lid - qopqoq",
    "design - dizayn; loyihalash",
    "sponsor - homiy; homiylik qilmoq",
    "senior - katta; tajribali",
    "condition - shart; holat",
    "check in - ro‘yxatdan o‘tmoq",
    "personality - shaxsiyat",
    "cartoon - multfilm",
    "math - matematika",
    "layer - qatlam",
    "caterer - taomnoma tashkilotchisi",
    "patient - sabrli; bemor",
    "cave - g‘or",
    "pin - igna; mixlamoq",
    "address - manzil; murojaat qilmoq",
    "fill out - to‘ldirmoq (shaklni)",
    "freshman - birinchi kurs talabasi",
    "crossword - krossvord",
    "vagina - qin",
    "cheek - yonoq",
    "progress - rivojlanish; taraqqiyot",
    "help out - yordam bermoq",
    "wee - kichkina; juda oz",
    "tailor - tikuvchi; moslashtirmoq",
    "fall for - sevib qolmoq; ishonmoq",
    "moon - oy",
    "section - bo‘lim; qism",
    "attorney - advokat; yurist",
    "fossil - qazilma",
    "pronounce - talaffuz qilmoq",
    "snake - ilon",
    "recover - sog‘aymoq; tiklanmoq",
    "nerve - nerv; jur’at",
    "offense - hujum; jinoyat",
    "stone - tosh",
    "goose - g‘oz",
    "relax - dam olmoq; bo‘shashmoq",
    "sentence - gap; hukm chiqarish",
    "shark - akula",
    "overhear - tasodifan eshitmoq",
    "buffet - bufet; ovqatni o‘ziga olish tizimi",
    "attitude - munosabat",
    "stamp - muhr; tamg‘a bosmoq",
    "emotion - hissiyot",
    "entertainment - ko‘ngilochar",
    "complaint - shikoyat",
    "call in - chaqirmoq; murojaat qilmoq",
    "pleasant - yoqimli",
    "sacrifice - qurbonlik; qurbonlik qilmoq",
    "laser - lazer",
    "score - hisob; baho olish",
    "attach - biriktirmoq",
    "directly - to‘g‘ridan-to‘g‘ri",
    "meanwhile - shu bilan birga; ayni",
    "witness - guvoh; guvohlik bermoq",
    "overreact - haddan tashqari reaksiya qilmoq",
    "comment - izoh; izoh bermoq",
    "smooth - silliq; yumshatmoq",
    "treatment - muolaja; muomala",
    "reporter - muxbir",
    "double - ikki hissa; ikki barobar qilmoq",
    "destiny - taqdir",
    "maintenance - texnik xizmat; qo‘llab-quvvatlash",
    "plant - o‘simlik; zavod",
    "spleen - taloq (organ)",
    "awfully - juda; qo‘rqinchli tarzda",
    "judgement - hukm; qaror",
    "once again - yana bir bor",
    "noon - peshin",
    "goodness - yaxshilik",
    "accountant - buxgalter",
    "kindergarten - bog‘cha",
    "entirely - butunlay; to‘liq",
    "thirsty - chanqagan",
    "tragic - fojeali",
    "coworker - hamkasb",
    "tan - qoramag‘iz rang; quyoshda qoraymoq",
    "statement - bayonot; izoh",
    "batch - partiya; guruh",
    "meet with - uchrashmoq",
    "accomplish - amalga oshirmoq",
    "estate - mulk; yer",
    "pay - to‘lamoq; haq",
    "fellow - do‘st; hamkasb",
    "mission - vazifa; topshiriq",
    "strategy - strategiya",
    "vow - qasam; qasam ichmoq",
    "staff - xodimlar",
    "motel - motel; yo‘l bo‘yidagi mehmonxona",
    "arrest - hibsga olish; qamoq",
    "choke - bo‘g‘moq; tiqilib qolmoq",
    "mint - yalpiz; yangi",
    "silver - kumush",
    "muscle - mushak",
    "ham - dudlangan go‘sht (cho‘chqa yoki boshqa go‘sht)",
    "polite - muloyim; xushmuomala",
    "macaroni - makaron",
    "traditional - an’anaviy",
    "bagel - halqa shaklidagi nondan mahsulot",
    "sob - ingrab yig‘lamoq",
    "potential - potensial; imkoniyat",
    "moral - axloqiy; xulosa",
    "blow - zarba; puflamoq",
    "lend - qarz bermoq",
    "defense - himoya",
    "north - shimol",
    "kidney - buyrak",
    "tuna - tuvali baliq",
    "sit around - bekor o‘tirib qolmoq",
    "skill - ko‘nikma; mahorat",
    "loudly - baland ovozda",
    "keep up - yetib bormoq; davom ettirmoq",
    "vet - veterinar",
    "access - kirish; foydalanish huquqi",
    "throw out - uloqtirmoq; chiqarmoq",
    "society - jamiyat",
    "rabbit - quyon",
    "garden - bog‘",
    "frankly - ochiqchasiga; samimiy",
    "exchange - almashish; almashmoq",
    "faith - ishonch; e’tiqod",
    "slice - bo‘lak; bo‘laklamoq",
    "slight - engil; ahamiyatsiz",
    "sink - cho‘kmoq; rakovina",
    "drive - haydamoq; harakatga keltirmoq",
    "print - chop etmoq",
    "upbeat - ijobiy; xursand",
    "bacon - dudlangan cho‘chqa go‘shti",
    "spider - o‘rgimchak",
    "acting - ijro; harakat",
    "silence - jimlik; sukutga keltirmoq",
    "liberty - erkinlik",
    "call for - talab qilmoq; chaqirmoq",
    "collection - to‘plam",
    "soccer - futbol",
    "relate - bog‘liq bo‘lmoq; hikoya qilmoq",
    "correct - to‘g‘ri; to‘g‘rilamoq",
    "government - hukumat",
    "unexpected - kutilmagan",
    "puzzle - jumboq; chalkashtirmoq",
    "suite - xona to‘plami (mehmonxonada)",
    "spring - bahor; buloq; sakramoq",
    "take over - egallamoq; boshqaruvni qo‘lga olmoq",
    "invest - investitsiya qilmoq",
    "starve - ochlikdan qiynalmoq",
    "era - davr; zamon",
    "custody - qamoq; vasiylik",
    "wind up - yakunlamoq; tugatmoq",
    "harm - zarar; zarar yetkazmoq",
    "east - sharq",
    "loan - qarz; kredit",
    "stretch - cho‘zmoq; cho‘zilish",
    "resource - resurs; manba",
    "allergy - allergiya",
    "accounting - buxgalteriya; hisob-kitob",
    "backpack - ryukzak",
    "pudding - puding",
    "folder - papka",
    "cabinet - shkaf; kabinet",
    "luckily - baxtimizga; omadimizga",
    "imaginary - tasavvurdagi; xayoliy",
    "maternity - onalik; tug‘ruq bilan bog‘liq",
    "freedom - erkinlik",
    "wolf - bo‘ri",
    "look through - ko‘z yugurtirmoq; ko‘rib chiqmoq",
    "snore - xurrak otmoq",
    "map - xarita",
    "nun - rohiba",
    "fax - faks; faks yubormoq",
    "suspicious - shubhali",
    "as far as - qadar; xususida",
    "crooked - egri; halol bo‘lmagan",
    "wise - dono; aqlli",
    "press - bosmoq; matbuot",
    "certificate - sertifikat; guvohnoma",
    "photographer - fotograf",
    "hunt - ov; ov qilmoq",
    "applause - olqish",
    "national - milliy",
    "crew - jamoa; ekipaj",
    "bid - taklif; narx taklif qilmoq",
    "celebrity - mashhur odam; yulduz",
    "chime - jarang; jaranglamoq",
    "angle - burchak; nuqtai nazar",
    "diversity - xilma-xillik",
    "sprinkle - sepmoq; sochmoq",
    "gardener - bog‘bon",
    "sin - gunoh; gunoh qilmoq",
    "trap - tuzoq; tuzoqqa tushirmoq",
    "owner - egasi",
    "junior - yoshroq; quyi darajadagi",
    "financial - moliyaviy",
    "wonder - hayrat; hayratlanmoq",
    "powerful - kuchli; ta’sirli",
    "satisfy - qondirmoq; mamnun qilmoq",
    "combination - kombinatsiya; qo‘shilish",
    "advance - oldinga siljish; oldindan",
    "fabulous - ajoyib; ertaklardagi",
    "writer - yozuvchi",
    "knowledge - bilim",
    "drop off - tushirib qo‘ymoq; olib borib qo‘ymoq",
    "back up - zaxira qilmoq; qo‘llab-quvvatlamoq",
    "puppet - qo‘g‘irchoq",
    "depend on - bog‘liq bo‘lmoq; ishonmoq",
    "shorts - shortik",
    "receipt - chek; kvitansiya",
    "pure - sof; toza",
    "cost - narx; narxga ega bo‘lmoq",
    "river - daryo",
    "response - javob",
    "coincidence - tasodif",
    "limit - chegaralamoq; chegara",
    "violence - zo‘ravonlik",
    "pump - nasos; nasos bilan chiqarib olmoq",
    "leaf - barg",
    "naughty - sho‘x; quv",
    "supply - yetkazib bermoq; ta’minot",
    "spare - ortiqcha; ayamoq",
    "background - orqa fon; kelib chiqish",
    "pirate - qaroqchi",
    "musical - musiqiy; musiqali",
    "push - itarmoq; bosim",
    "fortune - boylik; taqdir",
    "ending - yakun; oxir",
    "expression - ifoda",
    "kisser - o‘pishadigan odam; yuz",
    "collect - yig‘moq; jamlamoq",
    "flat - kvartira; tekis",
    "fit in - mos kelmoq; qo‘shilmoq",
    "evil - yomonlik; yovuzlik",
    "practice - amaliyot; shug‘ullanmoq",
    "welcome - hush kelibsiz; qabul qilmoq",
    "flash - yalt etmoq; yaltirash",
    "on board - bortda; qatnashayotgan",
    "sail - yelkan; suzmoq (kemada)",
    "unusual - noodatiy",
    "tip - maslahat; uchlik",
    "phone - telefon; telefon qilmoq",
    "blackmail - shantaj; shantaj qilmoq",
    "snow - qor; qor yog‘moq",
    "good - looking - chiroyli; ko‘rkam",
    "blessing - baraka; duo",
    "eyebrow - qosh",
    "savings - jamg‘arma",
    "lazy - dangasa",
    "meaningless - ma’nosiz",
    "demand - talab; talab qilmoq",
    "badge - belgi; nishon",
    "obsess - fikrga berilib ketmoq",
    "international - xalqaro",
    "backwards - orqaga; teskariga",
    "for sure - aniq; shubhasiz",
    "perfume - atir",
    "lotion - loson",
    "bro - aka; do‘st",
    "flavor - ta’m; hid",
    "backup - zaxira; yordam",
    "bite - tishlamoq; chaqmoq",
    "leader - yetakchi",
    "budget - byudjet; xarajatlar rejasi",
    "phalange - barmoq suyaklari (falanga)",
    "punishment - jazo",
    "haunt - ta’qib qilmoq; boshidan",
    "shock - hayrat; hayratlantirmoq",
    "put up - joylashtirmoq; chidamoq",
    "tape - lenta; tasma",
    "ship - kema; jo‘natmoq",
    "skinny - ozg‘in; ingichka",
    "prescription - resept; buyruq",
    "journal - jurnal",
    "homework - uy vazifasi",
    "sushi - suşi (yapon taomi)",
    "burn down - yonib ketmoq; kuymoq",
    "in public - omma oldida",
    "extremely - nihoyatda; juda",
    "necklace - marjon; bo‘yin tasmasi",
    "gravy - qayla (go‘sht yoki sabzavot suyuqligi)",
    "pack up - yig‘ishtirmoq",
    "accuse - ayblamoq",
    "sweat - ter; terlamoq",
    "darling - azizim; jonim",
    "example - misol; namuna",
    "take up - boshlamoq; egallamoq",
    "pearl - marvarid",
    "paradise - jannat",
    "ambulance - tez yordam mashinasi",
    "old - fashioned - eskicha; modadan qolgan",
    "mow - o‘t o‘rmoq",
    "entertain - ko‘ngil ochmoq",
    "delightful - zavqli; yoqimli",
    "pray - ibodat qilmoq; duo qilmoq",
    "slave - qul",
    "marathon - marafon",
    "heal - davolamoq; sog‘aymoq",
    "surely - shubhasiz; albatta",
    "deeply - chuqur; nihoyatda",
    "mumble - g‘o‘ldiramoq",
    "for example - masalan",
    "rescue - qutqarish; qutqarmoq",
    "cruel - shafqatsiz",
    "pact - shartnoma; kelishuv",
    "planet - sayyora",
    "brag - maqtanmoq",
    "flame - alanga",
    "undo - bekor qilmoq; yechmoq",
    "yogurt - yogurt",
    "steel - po‘lat",
    "develop - rivojlantirmoq; ishlab chiqmoq",
    "express - ifoda qilmoq; bildirmoq",
    "boxer - bokschi",
    "brush - cho'tka; tozalamoq",
    "fall off - yiqilib tushmoq; kamaymoq",
    "leave out - tashlab ketmoq;",
    "fur - mo‘yna; jun",
    "tile - plitka; cherepitsa",
    "newspaper - gazeta",
    "at stake - xavf ostida",
    "cent - sent (valyuta birligi)",
    "phrase - ibora; jumla",
    "pigeon - kaptar",
    "bitter - achchiq; iztirobli",
    "hoop - halqa",
    "gate - darvoza; eshik",
    "spicy - achchiq (taom); mazali",
    "secretary - kotib(a)",
    "contraction - qisqarish; qisqargan shakl (grammatika)",
    "antique - qadimiy; eski buyum",
    "clue - ishora; kalit",
    "comedy - komediya",
    "pole - ustun; tayoq",
    "whip - qamchi; qamchilamoq",
    "liquor - spirtli ichimlik",
    "ordinary - oddiy; odatdagi",
    "firm - qattiq; qat’iy; firma",
    "reaction - reaksiyalar; javob",
    "metal - metall",
    "direction - yo‘nalish; ko‘rsatma",
    "cabin - kabina; kulba",
    "underpants - ichki kiyim",
    "vegetable - sabzavot",
    "sudden - kutilmagan; to‘satdan",
    "shine - porlash; yorqin bo‘lmoq",
    "wreck - halokat; vayron qilmoq",
    "fully - to‘liq; mutlaqo",
    "toothbrush - tish cho‘tkasi",
    "claim - da’vo qilmoq; talab qilmoq",
    "supermarket - supermarket",
    "application - ariza; ilova",
    "contestant - ishtirokchi",
    "booth - do‘kon; chiqish joyi",
    "storm - bo‘ron",
    "happily - baxtli; xursand",
    "kick in - ishga tushirmoq; qo‘shilmoq",
    "spit - tupurmoq",
    "foundation - poydevor; asos",
    "instinct - instinkt; sezgi",
    "beard - soqol",
    "pull over - to‘xtamoq (avtomobil)",
    "involve in - ishtirok etmoq",
    "electricity - elektr energiyasi",
    "arrange - tartibga solmoq; joylashtirmoq",
    "porch - veranda",
    "partly - qisman",
    "seed - urug‘",
    "anonymous - noma’lum; anonim",
    "exam - imtihon",
    "fool - ahmoq; befoyda odam",
    "guarantee - kafolat",
    "separate - ajratmoq",
    "alert - ogohlantirish; hushyor",
    "rhyme - ohangdorlik; qo‘shiq qoidasi",
    "gain - foyda; oshirmoq",
    "ancient - qadimiy",
    "train - poezd; mashq qilmoq",
    "stab - pichoq bilan urmoq",
    "resolution - qaror; oldiga qo'yilgan maqsad",
    "inch - dyuym (o‘lchov birligi)",
    "experienced - tajribali",
    "messy - tartibsiz; to‘polon",
    "coast - sohil",
    "interview - intervyu; suhbat",
    "check on - tekshirib ko‘rmoq",
    "admire - hayratda bo‘lmoq; maqtamoq",
    "shove - itarish",
    "weather - ob-havo",
    "bull - erkak buqa",
    "beet - qizil lavlagi",
    "honesty - halollik",
    "handcuff - qo‘lqop (politsiya)",
    "drop by - tashrif buyurmoq",
    "grave - qabir; jiddiy",
    "mysterious - sirli",
    "resume - rezyume; qayta boshlamoq",
    "resident - yashovchi",
    "terribly - dahshatli; juda yomon",
    "petty - kichik; ahamiyatsiz",
    "foster - o‘stirmoq; tarbiyalamoq",
    "toner - tonik",
    "prayer - du‘o",
    "cloud - bulut",
    "toaster - tost qilish apparati",
    "motive - motiv; sabab",
    "alliance - ittifoq",
    "priority - ustunlik",
    "warrant - ruxsatnoma; guvohnoma",
    "counseling - maslahat berish; psixologik yordam",
    "charm - joziba",
    "fascinate - jalb qilmoq",
    "pencil - qarama; qalam",
    "worm - qurt",
    "heel - poyabzalning orqa qismi",
    "gang - jamoa; guruh",
    "blast - portlash; kuchli tovush",
    "geek - texnologiya ixlosmandi;",
    "menu - menyu",
    "goal - maqsad; gol (futbol)",
    "shell - qobiq",
    "experiment - tajriba",
    "vomit - qusmoq",
    "thankful - minnatdor",
    "tequila - tekila (alkogolli ichimlik)",
    "effect - ta’sir",
    "bomb - bomba",
    "absolute - mutlaq; to‘liq",
    "fling - uloqtirmoq; tashlamoq",
    "actress - aktrisa",
    "suitcase - chamadon",
    "balance - muvozanat; tenglik",
    "charm - joziba",
    "catholic - katolik",
    "medium - o‘rta daraja; vosita",
    "sack - qop; ishdan bo‘shatmoq",
    "block - blok; to‘sqinlik qilish",
    "lemon - limon",
    "resist - qarshilik ko‘rsatmoq",
    "erase - o‘chirmoq",
    "complicated - murakkab",
    "ink - siyoh",
    "annual - yillik",
    "threat - tahdid",
    "avenue - prospekt",
    "dime - cent (AQShda)",
    "waffle - vafli",
    "capital - poytaxt; kapital",
    "tense - xafa; asabiy",
    "violent - zo‘ravon",
    "surprisingly - ajablanarli tarzda",
    "mellow - yumshoq",
    "fall out - janjallashmoq; tushmoq",
    "for instance - masalan",
    "raspberry - malina",
    "bleed - qonamoq",
    "nickel - nickel (AQShda pul birligi)",
    "missing - yo‘qolgan; yetishmayotgan",
    "sneeze - aksirish",
    "evolution - evolyutsiya; taraqqiyot",
    "scale - shkal; miqyos",
    "briefcase - portfel",
    "telephone - telefon",
    "copier - ko‘paytirish apparati",
    "academy - akademiya",
    "wrestle - kurashmoq",
    "purchase - sotib olish",
    "cry out - baqirmoq",
    "cord - sim",
    "authority - hokimiyat",
    "coconut - kokos",
    "brownie - brauni (shirinlik)",
    "mailman - pochta xodimi",
    "smash - sindirmoq",
    "unfortunate - baxtsizlik",
    "ability - qobiliyat",
    "display - namoyish",
    "dull - xiralashgan; zerikarli",
    "chat - suhbat",
    "cater - taom xizmatini ko‘rsatmoq",
    "pause - tanaffus",
    "lamb - qo‘ziqorin; bola qoramol",
    "suburb - shahar chekkasi",
    "claw - tirnoq",
    "album - albom",
    "glue - yopishqoq; yopishtirmoq",
    "carton - karton quti",
    "growl - o‘rgimchak ovozi; g‘uvurlamoq",
    "nasty - jirkanch; baxtsiz",
    "confront - yuzma-yuz kela turib gapirmoq",
    "bring back - qaytarib olib kelmoq",
    "lobby - kutish zali; lobbi",
    "exchange - almashish; o‘rinbosar",
    "principle - printsip",
    "reasonable - mantiqli",
    "visitor - mehmon",
    "rob - o‘g‘irlamoq",
    "series - seriya; qator",
    "frozen - muzlagan",
    "carefully - ehtiyotkorlik bilan",
    "settle down - joylashmoq; tinchlanmoq",
    "upper - yuqori",
    "watch out - ehtiyot bo‘lmoq",
    "comfort - qulaylik",
    "stand by - yordam berish",
    "flow - oqim; to‘kilmoq",
    "curiosity - qiziqish",
    "bloody - qonli",
    "assure - ishonch hosil qilmoq",
    "vibe - atmosferaning sezgisi",
    "drape - pardalar; yopingan",
    "vampire - vampir",
    "sigh - nafas olish",
    "steam - bug‘",
    "silent - jim",
    "cage - qafas",
    "maker - ishlab chiqaruvchi",
    "tragedy - tragediya",
    "bakery - nonvoyxona",
    "handle - tutqich; boshqarish",
    "challenge - chaqiruv; sinov",
    "pepper - murch",
    "umbrella - yomg‘ir chadori",
    "fighter - jangchi",
    "luggage - yuk",
    "wire - sim",
    "care for - g‘amxo‘rlik qilmoq",
    "pierce - teshmoq",
    "tunnel - tunnel",
    "declare - e’lon qilmoq",
    "thunder - momaqaldiroq",
    "convention - anjuman; kelishuv",
    "warning - ogohlantirish",
    "doorbell - eshik qo‘ng‘irog‘i",
    "valuable - qimmatli",
    "minister - vazir",
    "constant - doimiy; o‘zgarmas",
    "activity - faoliyat",
    "downtown - shaharning markaziy qismi",
    "as a matter of fact - aslida; haqiqatda",
    "romance - romantika; sevgi",
    "rib - qovurg‘a",
    "policeman - politsiya xodimi",
    "rot - chirimoq",
    "recent - so‘nggi; yaqindagi",
    "proudly - faxr bilan",
    "legend - afsona; hikoya",
    "forgiveness - kechirim",
    "online - internet orqali",
    "youth - yoshlik; yosh avlod",
    "withdraw - chekinmoq; pulni yechib olmoq",
    "gamble - qimor o‘ynash; xavf ostiga qo‘ymoq",
    "return - qaytmoq; qaytarib bermoq",
    "tonight - bugun kechqurun",
    "kingdom - qirollik",
    "define - ta’riflamoq",
    "coal - ko‘mir",
    "ash - kul",
    "thud - tushish ovozi; do‘mbira ovozi",
]